### ISSUE TITLE
Problem with recorded audio file.

### ISSUE THREAD

**Issue by axzxc1236** [RedKenrok/node-audiorecorder#1]
For some reason computer programs seem to think the audio file has 18 hour of content (in file property), so I am having problem to upload the audio file to APIs, I wonder if you can fix this problem.

I am running sox 14.4.1rc3, the program is running on a Windows 10 system.

I am running codes like this

```
let audioRecorder = new AudioRecorder(options, console);
let file = fs.createWriteStream('recording.wav', { encoding: 'binary' });
 
// Start and write to the file.
audioRecorder.start().stream().pipe(file);

setTimeout(function() {
	audioRecorder.stop();
},10000);
```

**Comment by RedKenrok** [comment]
Interesting I'll have a look at it.

**Comment by axzxc1236** [comment]
sure.

```
// Imports modules.
const fs = require('fs');
const AudioRecorder = require('node-audiorecorder');

const options = {
  // Amount of channels to record.
  channels: 1,
  // Recording device to use.
  device: null,
  // Which program to use, either 'arecord', 'sox', and 'rec'.
  program: 'sox',
  // Audio sample rate in hz.
  sampleRate: 16000,
  // Time of silence in seconds before it stops recording.
  silence: 20,
  // Silence threshold (only for 'sox' and 'rec').
  threshold: 0.5,
  // Silence threshold to start recording, overrides threshold (only for 'sox' and 'rec').
  thresholdStart: null,
  // Silence threshold to stop recording, overrides threshold (only for 'sox' and 'rec').
  thresholdStop: null,
};
 
// Initialize recorder and file stream.
let audioRecorder = new AudioRecorder(options, console);
let file = fs.createWriteStream('recording.wav', { encoding: 'binary' });
 
// Start and write to the file.
audioRecorder.start().stream().pipe(file);

setTimeout(function() {
	audioRecorder.stop();
},10000);
```

**Comment by RedKenrok** [comment]
First of in the script you provided a threshold for when to start recording is set, however the program already exists before that. Try removing the threshold so you are left with:
```javascript
// Imports modules.
const fs = require('fs');
const AudioRecorder = require('node-audiorecorder');

const options = {
  // Amount of channels to record.
  channels: 1,
  // Recording device to use.
  device: null,
  // Which program to use, either 'arecord', 'sox', and 'rec'.
  program: 'sox',
  // Audio sample rate in hz.
  sampleRate: 16000,
  // Time of silence in seconds before it stops recording.
  silence: 0
};
 
// Initialize recorder and file stream.
let audioRecorder = new AudioRecorder(options, console);
let file = fs.createWriteStream('recording.wav', { encoding: 'binary' });
 
// Start and write to the file.
audioRecorder.start().stream().pipe(file);

setTimeout(function() {
	audioRecorder.stop();
}, 10000);
```
This makes sure it start recording from when the start function is called to the moment the stop function is called. I recommend only using the silence parameter if you programs lives long enough and does not write it to a file.

Secondly if I run the included example.js or the script provided by you I get the accurate time signature (See the images included below). Could you try running the example.js script included in this repository and see if that delivers any working results. Perhaps you could elaborate with some more detail if I am misunderstanding the issue.

![_recordingtest_details](https://user-images.githubusercontent.com/1876222/42326858-a2085300-806a-11e8-8737-06097f82a4c0.png)
![_recordingtest_editing](https://user-images.githubusercontent.com/1876222/42326859-a2277320-806a-11e8-8b8c-ab96c91157f9.png)

**Comment by axzxc1236** [comment]
I used the code you provided, but I still have the same problem.

Audio file https://filebin.net/emrexntrkxgenxfc

properties picture https://i.imgur.com/qw7WQV8.png

**Comment by RedKenrok** [comment]
This is rather peculiar as on my computer it does indicate the correct duration of the recording.

![_recordingreturned_details](https://user-images.githubusercontent.com/1876222/42328608-03749d20-806f-11e8-96d3-336d231d0572.png)

**Comment by RedKenrok** [comment]
Perhaps, I wouldn't be surprised if it was. Unfortunately I won't be able to help you with that much. My Windows 10 OS build is up to date to and at build version ``17134.112``.

**Comment by axzxc1236** [comment]
I am still using 1709(16299.492), I guess either I have to upgrade to 1803 or try another solution.

**Comment by RedKenrok** [comment]
Do let me know if updating the system works for you, so I can successfully close the issue.

**Comment by axzxc1236** [comment]
I am afraid I can't do this soon, I am in a middle of developing a team project.
