### ISSUE TITLE
Generated sox command does not work

### ISSUE THREAD

**Issue by ageorgios** [RedKenrok/node-audiorecorder#2]
Hello,
the command generated from the library:
sox -V0 -q -L -r 16000 -c 1 -e signed-integer -b 16 -t wav -
shows the usage summary of sox
sox:      SoX v14.4.1
Usage summary: [gopts] [[fopts] infile]... [fopts] outfile [effect [effopt]]...

**Comment by RedKenrok** [comment]
Hello,

Sorry to hear you are having issues, I will look into it. First of a few additional questions.
* What operating system are you using?
* What options are you giving to the modules?

Kind regards,
Ron Dekker

**Comment by ageorgios** [comment]
Raspberry Pi with stretch is the platform
rec works ok! 

Thank you
