### ISSUE TITLE
Error: spawn sox ENOENT

### ISSUE THREAD

**Issue by CaiProgramming** [RedKenrok/node-audiorecorder#28]
Can't seem to get it to work on windows. ive installed the binaries 

`
AudioRecorder: Command 'sox -d -q -c 1 -r 16000 -t wav -V0 -L -b 16 -e signed-integer -'; Options: AUDIODEV (default), AUDIODRIVER: (default);
Writing new recording file at:  examples-recordings\qiix.wav
AudioRecorder: Started recording.
Press ctrl+c to exit.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn sox ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn sox',
  path: 'sox',
  spawnargs: [
    '-d',  '-q',
    '-c',  '1',
    '-r',  '16000',
    '-t',  'wav',
    '-V0', '-L',
    '-b',  '16',
    '-e',  'signed-integer',
    '-'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-audiorecorder-test@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-audiorecorder-test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cmart\AppData\Roaming\npm-cache\_logs\2021-01-06T20_42_46_527Z-debug.log

`

**Comment by CaiProgramming** [comment]
ok added env var for it but now getting 

AudioRecorder: Command 'sox -d -q -c 1 -r 16000 -t wav -V0 -L -b 16 -e signed-integer -'; Options: AUDIODEV (default), AUDIODRIVER: (default);
Writing new recording file at:  examples-recordings\odec.wav
AudioRecorder: Started recording.
Press ctrl+c to exit.
Recording ended.
Recording closed. Exit code:  false
AudioRecorder: Exit code '1'.

**Comment by CaiProgramming** [comment]
running the command i get 
sox FAIL sox: Sorry, there is no default audio device configured

**Comment by CaiProgramming** [comment]
also does this record system audio?

**Comment by RedKenrok** [comment]
To try and solve your issue you can try the following:
1. Which version of SoX are you using. On Windows if you are running version 14.4.2 or later try downgrading to version 14.4.1 instead and see if that works.
2. Check Window's sound settings and see which audio device is selected by default, and make sure the selected one is valid.
3. Run the command `sox -d -q -c 1 -r 16000 -t wav -V0 -L -b 16 -e signed-integer -` directly in your terminal and let me know what happens. You should see a rapid output of giberish characters and not an error.

And finally to answer your last question, yes it can record system audio. On Windows make sure that the device called "Stereo mix" is enabled and set that up as the recording device.
