### ISSUE TITLE
Error Code 1?

### ISSUE THREAD

**Issue by kingofsquirrel** [RedKenrok/node-audiorecorder#29]
**Description**: *Write a concise description of what problem you encountered.*
Hey, so my script exits with an error code of 1, It says:
AudioRecorder: Exit code '1'.
What exactly does that mean? For the code I just copied the exact code you stated as an example in your npm module and I specified two options, program: sox and encoding: LINEAR16?
Thanks for any help

**Write any additional context in place of this.**

**Comment by RedKenrok** [comment]
See the SoX documentation for possible encoding types: http://sox.sourceforge.net/sox.html (search for −e ENCODING on the page to find the section). As you can see LINEAR16 is not listed there. You could try one of the following options for encoding: signed-integer, unsigned-integer, floating-point.

**Comment by kingofsquirrel** [comment]
Hey, thanks alot for the answer, it works perfectly fine now! I did run into another problem tho, and I was wondering if there is any function to only stop the .stream() process?

**Comment by RedKenrok** [comment]
You can stop the streaming by disabling the library using the .stop() method. See https://github.com/RedKenrok/node-audiorecorder#methods.

**Comment by kingofsquirrel** [comment]
I did try that, but I get an error saying: NodeJs: write after end, and there is nothing in my program that could've caused that error except that .stream(), and I thought maybe I could stop the streaming and then stop the library so I wouldn't get the error.

**Comment by kingofsquirrel** [comment]
Just wondering, you can start the library, stop it and then start it again in the same script, right? Because if not that could've caused the error.
