### ISSUE TITLE
Pipe audio effects like a fake device

### ISSUE THREAD

**Issue by icaroerasmo** [RedKenrok/node-audiorecorder#30]
This isn't a issue from this lib but I'd like to know if there's any way I could send some .wav audios while recording. Like a fake microphone. It would make the sounds of .wav files I ran and this lib would simply record these songs.

**Comment by RedKenrok** [comment]
Like record the audio your system is playing? If you are using Windows then perhaps the stereo mix is what you are looking for: https://thegeekpage.com/stereo-mix/. You can record this device using this library. Otherwise if you want to simulate a microphone output then this is not the library you want to look at.

**Comment by icaroerasmo** [comment]
Actually I could manage to get this lib to record the audio I was sending to a fake microphone as I mentioned. Now I'm facing some issues regarding to the quality of the recording. I thought I could record like audacity does, recording even the periods there's no sound being played. Do you know any way of achieving this?

**Comment by icaroerasmo** [comment]
take a look at the function "setupAudioRecorder". You'll see how I set up a fake microphone and I pipe .wav files like this:
```
ffmpeg -re \
    -i ../guide-automator-puppeteer/resources/keysound.wav \
    -f s16le -ar 16000 -ac 1 - > /tmp/gapFakeMic
```
https://github.com/icaroerasmo/guide-automator-puppeteer/blob/feature/time-fix/br/com/guide-automator/libs/Recorder.js

**Comment by RedKenrok** [comment]
You could change the 'silence' option of the audio recorder and set it to false. This should disable the automatic stopping of recordings if silence is detected.
