### ISSUE TITLE
multi-child

### ISSUE THREAD

**Issue by jjinkou2** [RedKenrok/node-audiorecorder#36]
Is that possible to modify the code to have multiple childs. i would like to spawn 2 sox recorder ( one for the mic and a second one for another input).

I declared 2 instances of audio recorder but  the first one closed a soon as  the 2nd fired,

**Comment by RedKenrok** [comment]
Probably. If you look at the index.js you'll see how at the top a childProcess variable is defined. This is used by all instances of the audio recorder. If instead it is defined as a property on the class you probably be able to run multiple instances at once.

**Comment by RedKenrok** [comment]
I have added a pull request adding this feature to the library, but before I publish is could you give it a try as well and let me know if the changes work for you? See #37.

**Comment by jjinkou2** [comment]
if i invert the order of instance creation both files contain only the voicemeeter 
```javascript 
// Create an instance.
let microphoneRecorder = new AudioRecorder(options2, logger);
let audioRecorder = new AudioRecorder(options, logger);

**Comment by RedKenrok** [comment]
The object.assign creates a new object in the constructor so that shouldn't be a problem. It could be with how the pipe works, or perhaps sox itself. I don't have time today to delve further into it, but I'll try to do some testing and get back to you soon.

**Comment by jjinkou2** [comment]
i read a lot today about pipe / stream but i didn't  find something. That's really annoying. 
i 'll continue working on this , and if i find something , i'll get back here too.

**Comment by jjinkou2** [comment]
i made it work ! i just change my  code to pack the object initialisation close to the filestream . 
it works but i don't know why

```javascript 
// microphone
const fileNameMic =  "examples-recordings/microphone.wav";
const streamMic = fs.createWriteStream(fileNameMic, {encoding: 'binary'});
let microphoneRecorder = new AudioRecorder(options2, logger);
microphoneRecorder.start().stream().pipe(streamMic);

// audio
const fileNameSpeaker = "examples-recordings/speaker.wav";
const streamSpeaker = fs.createWriteStream(fileNameSpeaker, {encoding: 'binary'});
let audioRecorder = new AudioRecorder(options, logger);
audioRecorder.start().stream().pipe(streamSpeaker);
```

**Comment by jjinkou2** [comment]
could that be a pb with the environment variable ? 
```javascript 
// Setup environment variables.
        if (this._options.device) {
          this._command.options.env.AUDIODEV = this._options.device;
        }
        if (this._options.driver) {
          this._command.options.env.AUDIODRIVER = this._options.driver;
        }

**Comment by jjinkou2** [comment]
I tested it and it works perfectly !

**Comment by RedKenrok** [comment]
Awesome!
