### ISSUE TITLE
Exit code 1 

### ISSUE THREAD

**Issue by dadodasyra** [RedKenrok/node-audiorecorder#38]
**Description**: *Write a concise description of what problem you encountered.*
Hi, Im using the library on Windows with last node js version and last sox version.

```js
const AudioRecorder = require('node-audiorecorder');
let fs = require('fs');

const deviceId = 3; //vaio3 output

// Initialize recorder and file stream.
let audioRecorder = new AudioRecorder({
    device: deviceId, //will probably dont work
    program: 'sox',
    type: 'wav', // Format type
    silence: 0// Time of silence in seconds before it stops recording.
}, console);

// Log information on the following events.
const fileName = "output.wav";
console.log('Writing new recording file at:', fileName);
const fileStream = fs.createWriteStream(fileName, { encoding: 'binary' });

// Start and write to the file.
audioRecorder.start().stream().pipe(fileStream);
// Keep process alive.
process.stdin.resume();
console.warn('Press ctrl+c to exit.');

setTimeout(() => {
    audioRecorder.stop();
    console.log('Recording stopped.');
}, 7000);
```

So here is my code.
The problem is that on execution it just return a 1 exit code error.
```console
node .\recorder.js --trace-wa
rnings                              
AudioRecorder: Command 'sox -d -q -c 1 -r 16000 -t wav -V0 -L -b 16 -e signed-integer -'; Op
tions: AUDIODEV 3, AUDIODRIVER: (default);
Writing new recording file at: output.wav
AudioRecorder: Started recording.
Press ctrl+c to exit.
AudioRecorder: Exit code '1'.
AudioRecorder: Stopped recording.
Recording stopped.
```

And when I try to execute the command generated I get this 
`C:\Program Files (x86)\sox-14-4-2\sox.exe FAIL sox: Sorry, there is no default audio device
configured`
So I believe that this is a device problem. But, how can I choose the good device (on windows i remember you) ? So I wan't to use this one.
![image](https://user-images.githubusercontent.com/44753923/156844796-853f0e7e-0760-40b8-91d0-897bb0c20312.png)
With another old js lib to record (which is too complicated for me) I found this device id.

I'm stuck and I dont know how can I do now.
Thks

**Comment by dadodasyra** [comment]
Okay so with sox 1.14.1 I fixed the problem.
Now I'm searching how can I listen at any points **during** the recording. My goal is to record only moment after a peak of dB.
If you can help me I would be very happy :)

**Comment by RedKenrok** [comment]
Sounds iteresting. I haven't done something simliar with this library. However I have done a little bit of audio analysis for a different project in a different language before.

I recommend you set the type to raw which allows you to pipe the audio out as PCM data (http://sox.sourceforge.net/sox.html). You can then start analyzing the signal without having to worry about encoding or headers.

Keep in mind there are several diffrent ways to measure loudness. Decibels is just one way to express that information. Have a look at: https://en.wikipedia.org/wiki/Sound_level. I would recommend starting with calculating the root mean square (RMS) over a period of time: https://en.wikipedia.org/wiki/Root_mean_square.

Hope this helps you on your way!
