### ISSUE TITLE
Generated arecord command does not work on Raspberry PI

### ISSUE THREAD

**Issue by pfisterer** [RedKenrok/node-audiorecorder#5]
Hello @RedKenrok, Thanks a lot for your project - I'm currently playing around with it. However, I'm having a small issue with the generated arecord command on Raspian. This is my configuration:

```JavaScript
const audioRecorder = new AudioRecorder({
	program: "arecord",     		// Program to use (arecord, rec, sox)
	device: "sysdefault:CARD=1",	// Recording device to use
	channels: 1,        				// Channel count
	encoding: "signed-integer",	// Encoding type. (only for `rec` and `sox`)
	rate: 16000,       		 		// Sample rate
	type: "wav"			        		// Format type
}, console);
```
The command being executed is: `arecord -D sysdefault:CARD=1 -V0 -q -L -c 1 -r 16000 -t wav -f S16_LE -`. According to `arecord -h`, `-L` is `list device names` and causes the program to terminate after listing the devices.

Is there any way to change this behaviour? Currently, I have removed [this line](https://github.com/RedKenrok/node-audiorecorder/blob/master/library/index.js#L46) to make it work.

**Comment by pfisterer** [comment]
My system info (`uname -a`) is `Linux cam 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux` and `cat /etc/debian_version` gives `buster/sid`.

**Comment by RedKenrok** [comment]
I'll look into it. Give me a day or two and I'll have the module updated.

**Comment by pfisterer** [comment]
Great, thank you very much!

**Comment by RedKenrok** [comment]
Try the new version `1.3.0-beta.0` and let me know if that works. I've also opened up the `format` argument of the audio recorder options.

**Comment by RedKenrok** [comment]
I was wondering if you have had a change to try out the new beta version, if so could you let me know if it worked.

**Comment by pfisterer** [comment]
Yes, I'm still working on it. I'm currently struggling with the hardware mic; please allow a few more days for testing. Thanks a lot for your support.

**Comment by RedKenrok** [comment]
Of course no problem, just wanted to check in.

**Comment by pfisterer** [comment]
@RedKenrok It works, tnx a lot. 

Just had to find out that my recording device only supports a sample rate of 44100 - and arecord doesn't complain when asking for a 16k sample rate...
