### ISSUE TITLE
Make "Keep silence in results" optional

### ISSUE THREAD

**Issue by pgmann** [RedKenrok/node-audiorecorder#6]
**Category**: `Improvement`

**Problem description**: *Write a concise description of what problem this would solve.*
Silence is kept in at the end of a recording. I would rather not have the `-l` option.

**Solution description**: *Write a concise description of what you would like to see changed.*
Make the `-l` flag optional.

**Write any additional context in place of this.**

**Comment by RedKenrok** [comment]
Give me a few more minutes and an option called `keepSilence` will be added to the newest release. By default it is set to `true` in order to remain backwards compatible.

**Comment by RedKenrok** [comment]
Version `1.4.0` is up on npm try it out.
