### ISSUE TITLE
Capture speakers output and stream it to the web.

### ISSUE THREAD

**Issue by rajatlnweb** [RedKenrok/node-audiorecorder#9]
Hi @RedKenrok, I am looking for a npm package which can capture system speakers output and stream it on the web browser. I tried your library for this. But it's giving me **audioRecorder.start() is not a function** error.

Can you please help me with the same?

**Comment by RedKenrok** [comment]
Could you post more of the code so I have a better idea of how you are using the library. Perhaps I can find a mistake in there. Secondly what operating system are you using?
